// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    aws_project_region: 'us-east-1',
    aws_cognito_identity_pool_id: 'us-east-1:99bc8abd-5ff0-4e93-a7e1-76095ed4fa11',
    aws_cognito_region: 'us-east-1',
    aws_user_pools_id: 'us-east-1_xysZPQBet',
    aws_user_pools_web_client_id: '4k6pj21fh1pd1jbatb4iu8n5hf',
};

export default awsmobile;
